#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | grep wlp2s0 | awk '{print ($1)}')

if [ $status ]; then
  icon="NoW"
  text=""
  col="#f38ba8"
else
  icon="W"
  text="${essid}"
  col="#a6e3a1"
fi

if [[ "$1" == "--COL" ]]; then
  echo $col
elif [[ "$1" == "--ESSID" ]]; then
  echo $text
elif [[ "$1" == "--ICON" ]]; then
  echo $icon
fi
